---
title: "replication_overview"
output: html_document
---

Replication guide and tips

# General replication folder structre:

* `Replication.Rmd` runs all scripts needed for replication of Chapter 11 figures and tables
* `/code_formatting` contains R scripts for formatting table and figure outputs into the versions used in the text
*  `/data` stores data
* `/data/raw` contains raw data files (these are the only files needed for full replication)
* `/data/temp` optional file for intermediary data generated by replication code that can be optionally sourced to save time when running main replication code.
* `/figures` contains the figure outputs
* `/tables` contains the .tex files for tables generated by the main replication script
* `manuscript.tex` contains .tex file for the paper, which sources from output in `/figures` and `/tables`. Any time results change, the paper is automatically updated when the .tex file is recompiled.

# General `Replication.Rmd` structure

* Set up chunck (installations)
* Options chunk

These are often logical values for whether to load intermediary data files, run processes that take longer, run analysis containing identifiable data, etc. They are used later in the replication to determine whether to run parts of the code, etc.

* Result-specific script (in order in which it appears in the main manuscript)
For each of the above, 

## Checklist

## Examples

# Further details

## Data
- Hosted on Dataverse (incl. sample code)
- Hosted on Github

## Random number generation in Rmd 

Rmd doesn't always work for replicating results, see https://github.com/yihui/knitr/issues/274 for how to make results reproducible.

This is especially tricky when results rely on multiple random draws in parallel (using pasSapply, for example). For example, if you are assigning treatment N-times in an analysis where p-value is obtained from randomization inference, you need to make sure that the results are consistent every time the same "N" value is chosen. This can be one by using `set.seed()` inside the parallel apply function, as in:


